version: "3.9"

x-django-env: &django-env
  DJANGO_DEBUG: false
  DJANGO_SETTINGS_MODULE: payments.settings
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

  DATABASE_DB: ${DATABASE_DB}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}

  CELERY_BROKER_URL: ${CELERY_BROKER_URL}

x-app-image: &app-image ${IMAGE_TAG}

x-common-labels: &common-labels
  observability.app: payments
  observability.environment: ${SHARED_ENV}

networks:
  default:
    name: ${SHARED_NETWORK}
    external: true

services:
  payments:
    image: *app-image
    container_name: ${SHARED_ENV}_payments_app
    labels:
      <<: *common-labels
      observability.component: api
    environment:
      <<: *django-env
    ports:
      - "${API_PORT}:8000"
    restart: always

  celery_worker_high:
    image: *app-image
    container_name: ${SHARED_ENV}_payments_celery_worker_high
    labels:
      <<: *common-labels
      observability.component: celery-worker-high
    command: celery -A payments worker -Q payments.high -c 4 -l INFO
    environment:
      <<: *django-env
    restart: always

  celery_worker_low:
    image: *app-image
    container_name: ${SHARED_ENV}_payments_celery_worker_low
    labels:
      <<: *common-labels
      observability.component: celery-worker-low
    command: celery -A payments worker -Q payments.low -c 2 -l INFO
    environment:
      <<: *django-env
    restart: always

  celery_beat:
    image: *app-image
    container_name: ${SHARED_ENV}_payments_celery_beat
    labels:
      <<: *common-labels
      observability.component: celery-beat
    command: celery -A payments beat -l INFO
    environment:
      <<: *django-env
    restart: always
