# Generated by Django 5.2.11 on 2026-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeableevent',
            name='callback_destination',
            field=models.CharField(choices=[('SYSTEM', 'To owning System (default)'), ('SOURCE_SYSTEM', 'To the Source System that initiated the payment')], default='SYSTEM', help_text="Determines which system's webhook URL should receive webhooks for payments created from this ChargeableEvent.\n\n• SYSTEM: always send to this ChargeableEvent.system.webhook_url\n• SOURCE_SYSTEM: send to payment_intent.source_system.webhook_url (if set)", max_length=20),
        ),
        migrations.AlterField(
            model_name='system',
            name='hashed_api_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
