# Generated by Django 5.2.11 on 2026-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chargeableevent_callback_destination_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providercallbacklog',
            name='core_provid_process_214244_idx',
        ),
        migrations.RemoveField(
            model_name='providercallbacklog',
            name='processed',
        ),
        migrations.AddField(
            model_name='providercallbacklog',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received (queued)'), ('PROCESSING', 'Being processed'), ('PROCESSED', 'Successfully applied'), ('FAILED', 'Processing failed (retries possible)'), ('REJECTED', 'Signature/invalid → discarded'), ('IGNORED', 'Terminal txn or obsolete')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='providercallbacklog',
            index=models.Index(fields=['status', 'created_at'], name='core_provid_status_7dee77_idx'),
        ),
    ]
