# Generated by Django 5.2.11 on 2026-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_providercallbacklog_core_provid_process_214244_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercallbacklog',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('IGNORED', 'Ignored')], db_index=True, default='RECEIVED', max_length=20),
        ),
    ]
