# Generated by Django 5.2.11 on 2026-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_providercallbacklog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookdeliverylog',
            options={},
        ),
        migrations.AlterField(
            model_name='chargeableevent',
            name='callback_destination',
            field=models.CharField(choices=[('SYSTEM', 'To owning System (default)'), ('SOURCE_SYSTEM', 'To the Source System that initiated the payment')], default='SYSTEM', help_text="<b>Determines which system's webhook URL receives payment webhooks.</b><br><br>• <b>SYSTEM</b>: Always send to this ChargeableEvent.system.webhook_url.<br>• <b>SOURCE_SYSTEM</b>: Send to payment_intent.source_system.webhook_url if it exists. If no source system is set, the webhook will fall back to the owning ChargeableEvent.system.webhook_url.", max_length=20),
        ),
    ]
