# Generated by Django 6.0.5 on 2026-07-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chargeableevent_callback_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('REQUIRES_ACTION', 'Requires Customer Action'), ('PROCESSING', 'Processing'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially Captured'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=30),
        ),
    ]
