# Generated by Django 5.2.11 on 2026-02-27 12:08

import audit.mixins
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica database.')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('app_label', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('track_create', models.BooleanField(default=True)),
                ('track_update', models.BooleanField(default=True)),
                ('track_delete', models.BooleanField(default=True)),
                ('excluded_fields', models.JSONField(blank=True, default=list)),
                ('retention_days', models.PositiveIntegerField(default=2555)),
            ],
            options={
                'verbose_name': 'Audit Configuration',
                'verbose_name_plural': 'Audit Configurations',
                'ordering': ['app_label', 'model_name'],
                'unique_together': {('app_label', 'model_name')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica database.')),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.TextField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('bulk_operation', 'Bulk Operation'), ('system_event', 'System Event'), ('security_event', 'Security Event')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('api_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'event_type'], name='audit_audit_created_38ffa0_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['request_id'], name='audit_audit_request_06fe30_idx')],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False, help_text='Indicates whether this record has been synchronized with the replica database.')),
                ('request_id', models.UUIDField(editable=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.TextField()),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('is_secure', models.BooleanField(default=False)),
                ('view_name', models.CharField(blank=True, max_length=255, null=True)),
                ('view_args', models.JSONField(blank=True, null=True)),
                ('view_kwargs', models.JSONField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('api_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='audit_reque_started_7c491f_idx'), models.Index(fields=['ended_at'], name='audit_reque_ended_a_f6ffa4_idx'), models.Index(fields=['time_taken'], name='audit_reque_time_ta_6b98fe_idx'), models.Index(fields=['request_method'], name='audit_reque_request_865d49_idx'), models.Index(fields=['is_authenticated'], name='audit_reque_is_auth_cbcca9_idx'), models.Index(fields=['activity_name'], name='audit_reque_activit_c0dab5_idx'), models.Index(fields=['view_name'], name='audit_reque_view_na_ddf60d_idx')],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
